# Generated by Django 3.0.4 on 2020-05-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsaggregator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='savedNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('link', models.CharField(max_length=64)),
            ],
        ),
    ]
